### ISSUE TITLE
Axe Ban on Imperium TTT

### ISSUE THREAD

**Issue by SecretlyJewish** [R3DAu/AxEAPI-Lua#7]
[AxE HAMMER] An insignificant soul was smooshed bythe hammer! good work!

1. Add a space in-between "bythe".
2. Would be helpful if the ban shows how long the ban is, the reason of the ban and either the name of the banned player or the steam id. Thanks

-- Posted by a Jew

**Comment by R3DAu** [comment]
Hey, yep I will add this to the to-do list.

Thanks.

**Comment by R3DAu** [comment]
Has been fixed and will be deployed in the next version (1.3.78 -Rev: C).
